#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# grissom - FOSS compliance tools
#
# Copyright (c) 2013 Eric Le Bihan <eric.le.bihan.dev@free.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse
from gettext import gettext as _
from grissom import __version__
from grissom.common import sanitize_args, setup_i18n
from grissom.extractors import create_extractor

setup_i18n()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--version',
                        action='version',
                        version=__version__)
    parser.add_argument('filenames',
                        metavar='FILE',
                        nargs='+',
                        help=_('file to identify'))
    parser.add_argument('-o', '--output',
                        metavar='DIR',
                        help=_('set output directory'))

    args = parser.parse_args()

    for filename in sanitize_args(args.filenames):
        extractor = create_extractor(filename)
        print("Using extractor {0}".format(extractor.description))
        extractor.extract(args.output)

# vim: ts=4 sts=4 sw=4 et ai
