#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# grissom - FOSS compliance tools
#
# Copyright (c) 2013 Eric Le Bihan <eric.le.bihan.dev@free.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse
from gettext import gettext as _
from grissom import __version__
from grissom.common import setup_i18n
from grissom.binfmt.core import BinfmtFinder

setup_i18n()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--version',
                        action='version',
                        version=__version__)
    parser.add_argument('directory',
                        metavar='DIR',
                        help=_('directory to scan'))
    parser.add_argument('--include-libs', '-l',
                        action='store_true',
                        default=False,
                        help=_('include shared libraries'))
    parser.add_argument('--include-kmods', '-m',
                        action='store_true',
                        default=False,
                        help=_('include kernel modules'))

    args = parser.parse_args()

    finder = BinfmtFinder(args.include_libs, args.include_kmods)
    for result in finder.scan(args.directory):
        print(result)

# vim: ts=4 sts=4 sw=4 et ai
